# Generated by Django 2.2.2 on 2019-07-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20190724_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
